name: "Deploy CodigoFacilito"
#trigger
on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    #variables de entorno
    env:
      NAME: CodigoFacilito
    steps:
      #- uses: actions/checkout@v4
      - name: working dir
        run: ls -la

      - name: Action             
        uses: actions/checkout@v4
              #Repositoriode quien creo la accion/nombre@version
      - name: working dir after action
        run: ls -la

      - name: Visualizando archivo    
        run: echo $GITHUB_OUTPUT

      - name: Compartir valores entre jobs    
        run: echo "my_variable='Hola Mundo'" >> $GITHUB_OUTPUT

      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
      - run: echo "${{github.ref}}"
      - run: echo "Variable de entorno NAME = $NAME "
      
##clase 2
  second_job:
    #if: false activar o desactivar el job
    #if: ${{github.ref == 'refs/heads/main2'}}
    needs: deploy-codigofacilito
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      - run: echo "job 2"
