name: "Deploy CodigoFacilito"
#trigger
on:
  push:
    branches: ["main"]
jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    outputs:
      salidaJob1: ${{ steps.step_1.outputs.my_variable }}
    #variables de entorno
    env:
      NAME: CodigoFacilito
    steps:
      #- uses: actions/checkout@v4
      - name: working dir
        run: ls -la

      - name: Action
        uses: actions/checkout@v4
              #Repositoriode quien creo la accion/nombre@version
      - name: working dir after action
        run: ls -la

      - name: Visualizando archivo
        run: echo $GITHUB_OUTPUT

      - name: Compartir valores entre jobs
        id: step_1
        run: echo "my_variable='Hola Mundo'" >> $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

      - name: Generar archivo
        run: |
          echo "Archivo prueba" >> test.log

      - name: subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

      # - run: echo "Generar binario"
      # - run: echo "Publicar version"
      # - run: echo "${{github.ref}}"
      # - run: echo "Variable de entorno NAME = $NAME "
      
##clase 2
  second_job:
    #if: false #activar o desactivar el job
    #if: ${{github.ref == 'refs/heads/main2'}}
    needs: deploy-codigofacilito
    runs-on: ubuntu-latest
        #variables de entorno
    env:
      SALIDA: ${{ needs.deploy-codigofacilito.outputs.salidaJob1}}
    steps:
      ##- uses: actions/checkout@v4
      #- run: echo "job 2"
      - name: Visualizando valor
        run: echo $SALIDA

      - name: Descargar Artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: cat file
        run: cat test.log
