name: "Deploy CodigoFacilito"
#trigger
on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    #variables de entorno
    env:
      NAME: CodigoFacilito
    steps:
      #- uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
      - run: echo "${{github.ref}}"
      - run: echo "Variable de entorno NAME = $NAME "
##clase 2
  second_job:
    #if: false activar o desactivar el job
    if: ${{github.ref == 'refs/heads/main2'}}
    needs: deploy-codigofacilito
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v4
      - run: echo "job 2"
